apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-game
  namespace: default
  labels:
    app: sudoku
spec:
  replicas: 2  # మన సుడోకు గేమ్‌ని రెండు సర్వర్లలో సమానంగా రన్ చేస్తుంది (High Availability)
  selector:
    matchLabels:
      app: sudoku
  template:
    metadata:
      labels:
        app: sudoku
    spec:
      containers:
      - name: sudoku-container
        # FIXED: ఇమేజ్ పేరును 'super-counter' నుండి నీ అసలైన 'sudoku:latest' కి మార్చాం
        image: docker.io/shanmukharaomeesala/sudoku:latest 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "250m"
