apiVersion: v1
kind: Service
metadata:
  name: sudoku-service
  namespace: default
  labels:
    app: sudoku
spec:
  type: LoadBalancer
  selector:
    app: sudoku
  ports:
    - protocol: TCP
      port: 80         # బయటి ప్రపంచం (బ్రౌజర్) మన గేమ్‌ని చూసే పోర్ట్
      targetPort: 5000 # FIXED: లాగ్స్ లో వచ్చిన నీ ఫ్లాస్క్ యాప్ అసలైన పోర్ట్ 5000 కి రూట్ చేసాం
