apiVersion: v1
kind: Service
metadata:
  name: sudoku-service
  namespace: default
  labels:
    app: sudoku
spec:
  type: LoadBalancer
  selector:
    app: sudoku
  ports:
    - protocol: TCP
      port: 80         # బ్రౌజర్ లో మనం చూసే పబ్లిక్ పోర్ట్
      targetPort: 5000 # కంటైనర్ లోపల నీ ఫ్లాస్క్ యాప్ రన్ అవుతున్న అసలైన పోర్ట్
